---
- name: Include tasks for Debian Stretch
  include_tasks: stretch.yml
  when: ansible_distribution_release == "stretch"
  tags:
    - fail2ban

- name: Debian Bullseye and Buster
  block:

    - name: Install packages for Debian Bullseye and Buster
      apt:
        pkg:
          - iptables
          - iptables-persistent
          - nftables
          - netfilter-persistent
          - whois
          - python3-pyinotify
          - fail2ban

    - name: Filters in place
      copy:
        src: "files/filter.d/{{ file }}.conf"
        dest: "/etc/fail2ban/filter.d/{{ file }}.conf"
        mode: 0644
      loop:
        - wordpress-hard
        - wordpress-soft
      loop_control:
        loop_var: file

    - name: Enable iptables-legacy for ipv4
      command: update-alternatives --set iptables /usr/sbin/iptables-nft
      changed_when: false

    - name: Enable iptables-legacy for ipv6
      command: update-alternatives --set ip6tables /usr/sbin/ip6tables-nft
      changed_when: false

    - name: fail2ban jail.local in place
      template:
        src: templates/jail.local.j2
        dest: /etc/fail2ban/jail.local
        mode: 0644

  when: ansible_distribution_release != "stretch"
  tags:
    - fail2ban

- name: fail2ban restarted
  service:
    name: fail2ban
    state: restarted
  tags:
    - fail2ban
    - molecule-idempotence-notest
...
