---
- name: Install packages for Debian Stretch
  apt:
    pkg:
      - iptables
      - iptables-persistent
      - whois
      - python3-pyinotify
      - fail2ban
  tags:
    - fail2ban

- name: fail2ban filters in place
  copy:
    src: files/filter.d/
    dest: /etc/fail2ban/filter.d/
    mode: 0644
  tags:
    - fail2ban

- name: fail2ban jail.local in place
  template:
    src: templates/jail.local.stretch.j2
    dest: /etc/fail2ban/jail.local
    mode: 0644
  tags:
    - fail2ban
...
